### ISSUE TITLE
Module 04 - Runtime Error

### ISSUE THREAD

**Issue by 17110014-HICET-IT** [FYP-ITMS/Intelligent-Traffic-Management-System-Using-ML-YOLO#6]
Incorrect code in DSS Phase. Look out. @ashwin2125 @17110013-HICET-IT 

Dynamic Signal Switching Phase
Traceback (most recent call last):
  File "itms-yolov3.py", line 248, in <module>
    switch_signal(denser_lane, switching_time)
  File "/content/Intelligent-Traffic-Management-System-Using-ML-YOLO/util/dynamic_signal_switching.py", line 6, in switch_signal
    time("Calculating Signal Open/Close Timing..." + time.sleep(1) +
TypeError: can only concatenate str (not "NoneType") to str

**Comment by 17110014-HICET-IT** [comment]
Fixed it. 😍

**Comment by 17110009** [comment]
Great work.
